function CreateShipment() {
  return (
    <div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
      <div>createshipment</div>
    </div>
  );
}

export default CreateShipment;
